### ISSUE TITLE
some bugs + improvement suggestions

### ISSUE THREAD

**Issue by ghost** [Being-RAYtastic/Empo#1]
heya!
many websites block you if you try to scrape them, however this maybe fixed if u use evasion techniques like changing user agents, referers and proxies etc.....

i see you're just sending request to get text without any evasion technique...

to solve this i made  a library that can be used to send http requests + it has built-in evasion against being blocked from web scraping, however i wont guarantee 100% success, i would recommend to keep code under try catch blocks.....

the code for the library is

`request/__init__.py`
```
import random
import requests
import os

USER_AGENTS = [
               "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/37.0.2062.94 Chrome/37.0.2062.94 Safari/537.36",
               "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36",
               "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko",
               "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0",
               "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9"
]

REFERER = "https://google.com/"

headers = {
        "User-Agent": random.choice(USER_AGENTS),
        "Referer": REFERER
}

PROXIES = {
        "http": "socks5://127.0.0.1:9050",
        "https": "socks5://127.0.0.1:9050"
}


class get:
    def __init__(self, url):
        if os.getuid() != 0:
            raise Exception("Root privileges required!")

        os.system("systemctl reload tor.service")

        request = requests.get(url, headers=headers, proxies=PROXIES)

        self.url = url
        self.text = request.text
        self.status_code = request.status_code
```

the usage for this library is same as the popular requests module

some examples are:-

`test.py`
```
import request

r = request.get("https://google.com")

print(r.url) # prints the url
print(r.text) # prints the text/html code
print(r.status_code) #prints the http status code
```

+

this library requires `tor` and `pysocks` module so we may code a bash script to install dependencies and set up our project

NOTE:- YOU NEED TO HAVE ROOT PRIVILEGES TO SEND REQUESTS VIA THIS LIBRARY

+

you're getting side box result and main result from google at two different times, which is a very shitty way to doing, so try to improve it

**Comment by Being-RAYtastic** [comment]
Doesn't Work

**Comment by Being-RAYtastic** [comment]
Doesn't Work

**Comment by Being-RAYtastic** [comment]
Doesn't Work
